server:
  port: 8080
  servlet:
    context-path: /admin
spring:
  profiles:
    active: dev # 开发环境 生产则去掉
  application:
    name: nex-admin
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true  # 确保服务发现启用
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  #        ip: 127.0.0.1   # 注册 IP 为 127.0.0.1
  #        port: 8080      # 注册端口
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nex
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis # 默认为 none 配置为 redis 读写 session
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    sentinel:
      master: #mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
    host: 127.0.0.1
    port: 6379
    database: 1 # 默认使用 0 库
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 标准输出打印sql
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
platform:
    database-type: MySQL # 数据库类型
    api-permission:
      anons: # 不登录可访问